### ISSUE TITLE
[Chunk 3] three .timestamp files have nothing to do with ZCorp

### ISSUE THREAD

**Issue by TcTheTurtle** [ZPrograms-ZCorp/ZCorp-All-Files-1617#1]
Basically the title says it all. In the 3rd compressed chunk, the three timestamp files:
48ac84126bcac308.timestamp
ccac15159d6cac02.timestamp
cce3fe3b0d8d8002.timestamp

Have absolutely nothing to do with ZCorp. They have to do with other programs. One even something that we have never needed for it, "TestNav". I want these files to be removed.

**Comment by ZPrograms-ZCorp** [comment]
This issue has been fixed. Thank you for creating an issue.
